# Generated by Django 5.1.7 on 2025-03-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compras_lentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
                ('nota_fiscal', models.IntegerField()),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField()),
                ('sequencial', models.IntegerField()),
                ('referencia_fabricante', models.TextField(max_length=100)),
                ('observacao', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
