# Generated by Django 5.1.7 on 2025-03-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compras_lentes',
            new_name='ComprasLentes',
        ),
    ]
