# Generated by Django 5.1.7 on 2025-03-31 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0002_rename_compras_lentes_compraslentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraslentes',
            old_name='sequencial',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='compraslentes',
            old_name='descricao',
            new_name='descricao_lente',
        ),
        migrations.RemoveField(
            model_name='compraslentes',
            name='valor_custo',
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='custo_nota_fiscal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='custo_site',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='custo_tabela',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='data_liberacao_blu',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='duplicata',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='numero_pedido',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='ordem_servico',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='sequencial_savwin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compraslentes',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compraslentes',
            name='referencia_fabricante',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
