# Generated by Django 5.1.7 on 2025-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0003_rename_sequencial_compraslentes_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraslentes',
            name='loja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
