# Generated by Django 5.1.7 on 2025-04-03 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0005_alter_compraslentes_custo_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraslentes',
            name='sequencial_savwin',
            field=models.IntegerField(help_text='Número entre 1 e 99.999.999', validators=[django.core.validators.MinValueValidator(1, message='O valor mínimo é 1'), django.core.validators.MaxValueValidator(99999999, message='O valor máximo é 99.999.999')]),
        ),
    ]
