# Generated by Django 5.1.7 on 2025-04-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0006_alter_compraslentes_sequencial_savwin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraslentes',
            old_name='numero_pedido',
            new_name='num_pedido',
        ),
    ]
