# Generated by Django 5.1.7 on 2025-04-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0007_rename_numero_pedido_compraslentes_num_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraslentes',
            old_name='loja',
            new_name='num_loja',
        ),
    ]
