# Generated by Django 5.1.7 on 2025-04-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_site', '0008_rename_loja_compraslentes_num_loja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraslentes',
            old_name='ordem_servico',
            new_name='ordem_de_servico',
        ),
    ]
