# Generated by Django 5.1.7 on 2025-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen_temp', '0002_senhatemporaria_status_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senhatemporaria',
            name='status_uso',
        ),
        migrations.AddField(
            model_name='senhatemporaria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
