# Generated by Django 5.1.7 on 2025-04-14 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen_temp', '0003_remove_senhatemporaria_status_uso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senhatemporaria',
            name='criada_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 19, 27, 24, 535625, tzinfo=datetime.timezone.utc)),
        ),
    ]
