# Generated by Django 5.1.7 on 2025-04-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen_temp', '0004_alter_senhatemporaria_criada_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senhatemporaria',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
